# Generated by Django 5.0.3 on 2024-03-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_products', '0003_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
