# Generated by Django 5.0.3 on 2024-03-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_products', '0007_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
