# Generated by Django 5.0.3 on 2024-03-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_products', '0008_rename_products_product_rename_users_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='udate',
            field=models.DateField(auto_now=True),
        ),
    ]
