# Generated by Django 5.0.3 on 2024-03-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_products', '0009_user_udate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
