# Generated by Django 5.0.3 on 2024-03-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_products', '0011_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AddField(
            model_name='product',
            name='pimgpath',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
