# Generated by Django 5.0.3 on 2024-03-20 20:23

import gym_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_products', '0012_delete_uploadedfile_product_pimgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimgpath',
            field=models.FileField(null=True, upload_to=gym_products.models.Product.imgs_path),
        ),
    ]
